version: "3"

services:

  server:
    build:
      ./server
    ports:
      - 8080:80
#    network_mode: host
    restart: always
    volumes:
      - ./app:/app
    links:
      - php

  php:
    build:
      ./app
#    working_dir: /app
    volumes:
      - ./app:/app

  mysql:
    build:
      ./db
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: ""
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: etest
    volumes:
    - ./db/data:/var/lib/mysql
#    network_mode: host
    restart: always
